version: "3.8"
services:
    beoearth-server:
        container_name: beoearth-server
        build: .
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASS: ${POSTGRES_PASS}
            POSTGRES_DBNAME: ${POSTGRES_DBNAME}
            HOST_IP_ADDRESS: ${HOST_IP_ADDRESS}
            POSTGRES_PORT: ${POSTGRES_PORT}
            SERVER_PORT: ${SERVER_PORT}
        volumes:
            - ./target/server-1.0.0-SNAPSHOT.war:/usr/local/tomcat/webapps/server.war
        ports:
            - "${SERVER_PORT}:8080"
        restart: always
