version: "3.8"
services:
    tomcat:
        container_name: beoearth-server
        image: library/tomcat:9.0.36-jdk11
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASS: ${POSTGRES_PASS}
            POSTGRES_DBNAME: ${POSTGRES_DBNAME}
            POSTGIS_ADDRESS: ${POSTGIS_ADDRESS}
            POSTGRES_PORT: ${POSTGRES_PORT}
            SERVER_PORT: ${SERVER_PORT}
        volumes:
            - ./target/server-1.0.0-SNAPSHOT.war:/usr/local/tomcat/webapps/server.war
        ports:
            - "${SERVER_PORT}:8080"
        restart: always
